services:
  frontend:
    build:
      context: ./react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # volumes:
    #   - ./react-frontend:/app

  backend:
    build:
      context: ./flask-backend
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URL: mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    depends_on:
      - db
    entrypoint:
      ["./wait-for-it.sh", "db:3306", "--", "flask", "run", "--host=0.0.0.0"]
    # volumes:
    #   - ./flask-backend:/app

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
