services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URL: mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    depends_on:
      - db
    entrypoint:
      ["./wait-for-it.sh", "db:3306", "--", "flask", "run", "--host=0.0.0.0"]
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    volumes:
      - ./backend/migrations:/app/migrations

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
