"""pskiv added

Revision ID: 7abe482f42d8
Revises: de14f1ff7708
Create Date: 2024-11-25 06:55:45.430632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abe482f42d8'
down_revision = 'de14f1ff7708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pskiv', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pskiv')

    # ### end Alembic commands ###
